
name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - release/v0.1  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Deploy to PythonAnywhere
      env:
        PYTHONANYWHERE_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
      run: |
        git remote add pythonanywhere https://github.com/ABHIK19982/exam_prep_assistant
        git push pythonanywhere release/v1.0

    - name: Reload webapp
      uses: jensvog/pythonanywhere-webapp-reload-action@v1
      with:
        host: 'pythonanywhere.com'
        username: 'devpythonwebserver'
        api-token: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        domain-name: 'devpythonwebserver.pythonanywhere.com'
